# -*- coding: utf-8 -*-
"""namburi rakesh -Glowlogics Module Exam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFhaaJNA9p3gqsGSiVFjDlyF-CRA0kQI

# CASE STUDY

# Movie Ratings Analytics Company

## Scenario

You are a **Junior Data Analyst** working for a Movie Analytics Company.

The company wants to understand:

```text
Which movies are performing best?

Which genre is most popular?

Do higher-rated movies earn more revenue?

What is the average movie rating?

How can movie studios improve performance?
```

### Dataset Columns

| Column              | Meaning                   |
| :------------------ | :------------------------ |
| Movie_ID            | Movie Identifier          |
| Genre               | Movie Genre               |
| Duration_Minutes    | Movie Length              |
| IMDB_Rating         | Movie Rating              |
| Box_Office_Millions | Revenue Earned (Millions) |

---

# DAY 1

# Pandas Basics

## Goal

Understand the dataset.

### Q1

Import Pandas.
"""

import pandas as pd

# Commented out IPython magic to ensure Python compatibility.
# %%writefile movies.csv
# Movie_ID	Genre	Duration_Minutes	IMDB_Rating	Box_Office_Millions
# 4001	Thriller	168	6.8	77.3
# 4002	Thriller	155	6.1	132.1
# 4003	Action	125		276.1
# 4004	Comedy	177	9.5	437.8
# 4005	Action	98	6.2	222.4
# 4006		109	9.1	289.3
# 4007	Drama	154	6.6	440.9
# 4008	Action	-120	7.3	136.5
# 4009	Thriller	150	7.6	397.3
# 4010	Thriller	104	6.6	486.9
# 4011	Thriller	131	8.6	-50
# 4012	Drama	105	7.6	74.4
# 4013	Thriller	119	-1.5	277.4
# 4014	Thriller	166	9	35.9
# 4015	Drama	166	5.2	277.1
# 4016	Comedy	140	5.3	343.2
# 4017	Action	153	7.1	459.5
# 4018	Comedy	176	6.9	295.1
# 4019	Drama	152	7.2	305.8
# 4020	Drama	99	5.7	241.7
# 4004	Comedy	177	9.5	437.8
# 4009	Thriller	150	7.6	397.3

"""### Q2

Load the dataset.
"""

df = pd.read_csv('movies.csv', sep='\t')
print("Dataset loaded successfully!")

"""### Q3

Display first 5 records.
"""

display(df.head())

"""### Q4

Display last 5 records.
"""

display(df.tail())

"""### Q5

How many rows and columns exist?
"""

print(df.shape)

"""### Q6

Display all column names.
"""

print(df.columns)

"""### Q7

Display dataset information.
"""

df.info()

"""### Q8

Display summary statistics.
"""

display(df.describe())

"""## Business Question

### How many movies are in our dataset?
"""

print(len(df))

"""---

# Topic 2

# Filtering & Sorting

## Q1

Show movies with rating above 8.
"""

display(df[df['IMDB_Rating'] > 8])

"""## Q2

Show movies earning more than 300 million.
"""

display(df[df['Box_Office_Millions'] > 300])

"""## Q3

Show movies longer than 150 minutes.
"""

display(df[df['Duration_Minutes'] > 150])

"""## Q4

Show Action movies.
"""

display(df[df['Genre'] == 'Action'])

"""## Q5

Show movies with rating above 8 and revenue above 300 million.
"""

display(df[(df['IMDB_Rating'] > 8) & (df['Box_Office_Millions'] > 300)])

"""## Q6

Sort by IMDB Rating.

Highest first.
"""

display(df.sort_values(by='IMDB_Rating', ascending=False))

"""## Q7

Sort by Box Office Revenue.

Highest first.
"""

display(df.sort_values(by='Box_Office_Millions', ascending=False))

"""---

## Business Questions

## Which movie is rated highest?
"""

highest_rated_movie = df.loc[df['IMDB_Rating'].idxmax()]
display(highest_rated_movie)

"""## Which movie earned the most revenue?"""

most_revenue_movie = df.loc[df['Box_Office_Millions'].idxmax()]
display(most_revenue_movie)

"""## Which movies may need improvement?"""

display(df[(df['IMDB_Rating'] < 6) | (df['Box_Office_Millions'] < 100)])

"""---

# Topic 3

# Business Analysis & Feature Engineering

## Q1

Average Movie Rating
"""

average_rating = df['IMDB_Rating'].mean()
print(f"Average Movie Rating: {average_rating:.2f}")

"""## Q2

Average Movie Duration
"""

average_duration = df['Duration_Minutes'].mean()
print(f"Average Movie Duration: {average_duration:.2f} minutes")

"""## Q3

Average Box Office Revenue
"""

average_revenue = df['Box_Office_Millions'].mean()
print(f"Average Box Office Revenue: ${average_revenue:.2f} million")

"""## Q4

Maximum Rating
"""

max_rating = df['IMDB_Rating'].max()
print(f"Maximum Rating: {max_rating:.1f}")

"""## Q5

Minimum Rating
"""

min_rating = df['IMDB_Rating'].min()
print(f"Minimum Rating: {min_rating:.1f}")

"""## Q6

Maximum Revenue
"""

max_revenue = df['Box_Office_Millions'].max()
print(f"Maximum Revenue: ${max_revenue:.2f} million")

"""# Feature Engineering

## Create Movie Performance Category

Teacher Says:

```text
Rating Below 6
=
Poor

Rating 6 - 8
=
Average

Rating Above 8
=
Excellent
```
"""

min_revenue = df['Box_Office_Millions'].min()
print(f"Minimum Revenue: ${min_revenue:.2f} million")

"""### Create Function"""

def performance_category(rating):
    if rating < 6:
        return 'Poor'
    elif 6 <= rating <= 8:
        return 'Average'
    else:
        return 'Excellent'

"""### Create Performance_Category Column"""

df['Performance_Category'] = df['IMDB_Rating'].apply(performance_category)
display(df.head())

"""### Count Performance Categories"""

performance_counts = df['Performance_Category'].value_counts()
print(performance_counts)

"""---

# Business Questions

## How many movies are Poor?
"""

poor_movies = performance_counts['Poor']
print(f"Number of Poor movies: {poor_movies}")

"""## How many movies are Average?"""

average_movies = performance_counts['Average']
print(f"Number of Average movies: {average_movies}")

"""## How many movies are Excellent?"""

excellent_movies = performance_counts['Excellent']
print(f"Number of Excellent movies: {excellent_movies}")

"""## Where should studios focus improvement?"""

poor_performing_movies = df[df['Performance_Category'] == 'Poor']
display(poor_performing_movies)

print(poor_performing_movies['Genre'].value_counts())

"""---

# Topic 4

# Data Cleaning & Validation

## Q1

Check missing values.
"""

print(df.isnull().sum())

"""## Q2

Check duplicate records.
"""

print(df.duplicated().sum())

"""## Q3

Maximum Duration
"""

max_duration = df['Duration_Minutes'].max()
print(f"Maximum Duration: {max_duration} minutes")

"""## Q4

Minimum Duration
"""

min_duration = df['Duration_Minutes'].min()
print(f"Minimum Duration: {min_duration} minutes")

"""## Q5

Maximum Revenue
"""

max_revenue = df['Box_Office_Millions'].max()
print(f"Maximum Revenue: ${max_revenue:.2f} million")

"""## Q6

Can Duration be negative?
"""

negative_duration_movies = df[df['Duration_Minutes'] < 0]
if not negative_duration_movies.empty:
    print("Yes, there are movies with negative durations:")
    display(negative_duration_movies)
else:
    print("No, there are no movies with negative durations.")

"""## Q7

Can Rating be negative?
"""

negative_rating_movies = df[df['IMDB_Rating'] < 0]
if not negative_rating_movies.empty:
    print("Yes, there are movies with negative IMDB ratings:")
    display(negative_rating_movies)
else:
    print("No, there are no movies with negative IMDB ratings.")

"""## Q8

Can Revenue be negative?
"""

negative_revenue_movies = df[df['Box_Office_Millions'] < 0]
if not negative_revenue_movies.empty:
    print("Yes, there are movies with negative Box Office Millions:")
    display(negative_revenue_movies)
else:
    print("No, there are no movies with negative Box Office Millions.")

"""---

# Validation Rules

Movie Analytics Company Rules

```text
Duration > 0

IMDB Rating > 0

Box Office Revenue > 0
```
"""



"""## Business Question

### Can management trust this data?

### Student Answer

No, management cannot fully trust this data. Several data quality issues were identified:

*   **Missing Values:** There is 1 missing `Genre` and 1 missing `IMDB_Rating`.
*   **Duplicate Records:** There are 2 duplicate entries in the dataset.
*   **Negative `Duration_Minutes`:** At least one movie has a negative duration, which is impossible.
*   **Negative `IMDB_Rating`:** At least one movie has a negative IMDB rating, which is not possible as ratings are typically on a scale (e.g., 1-10 or 0-10).
*   **Negative `Box_Office_Millions`:** At least one movie has a negative box office revenue, which is not possible.

---

# Topic 5

# Matplotlib
"""



"""---

## Chart 1

Movie Ratings
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.hist(df['IMDB_Rating'].dropna(), bins=10, edgecolor='black')
plt.title('Distribution of IMDB Ratings')
plt.xlabel('IMDB Rating')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""### Observation

Which movie has the highest rating?

### Business Decision

```text
Promote highly-rated movies.
```
"""



"""---

## Chart 2

Revenue Distribution

### Observation

What revenue range is most common?

### Business Decision

```text
Identify profitable movie range.
```
"""

plt.figure(figsize=(10, 6))
plt.hist(df['Box_Office_Millions'].dropna(), bins=10, edgecolor='black')
plt.title('Distribution of Box Office Revenue (Millions)')
plt.xlabel('Box Office Revenue (Millions)')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(df['Duration_Minutes'].dropna(), bins=10, edgecolor='black')
plt.title('Distribution of Movie Durations (Minutes)')
plt.xlabel('Duration (Minutes)')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()



"""---

## Chart 3

Duration Distribution

### Observation

What movie length is most common?

### Business Decision

```text
Plan future productions accordingly.
```
"""

performance_counts = df['Performance_Category'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(performance_counts, labels=performance_counts.index, autopct='%1.1f%%', startangle=90, colors=['skyblue', 'lightcoral', 'lightgreen'])
plt.title('Distribution of Movie Performance Categories')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""---

## Chart 4

Performance Category Pie Chart

### Observation

What percentage of movies are Excellent?

### Business Decision

```text
Understand overall content quality.
```
"""

import seaborn as sns

plt.figure(figsize=(12, 7))
sns.barplot(x='Movie_ID', y='IMDB_Rating', data=df.sort_values(by='IMDB_Rating', ascending=False), palette='viridis', hue='Movie_ID', legend=False)
plt.title('Movie Ratings (Highest First)')
plt.xlabel('Movie ID')
plt.ylabel('IMDB Rating')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""---

# Topic 6

# Seaborn + Storytelling
"""



"""---

## Chart 1

Ratings Bar Chart
"""



"""### Observation

Which movies are most appreciated?

### Business Decision

```text
Study successful movies.
```
"""



"""---

## Chart 2

Revenue Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['Box_Office_Millions'].dropna(), bins=10, kde=True)
plt.title('Distribution of Box Office Revenue (Millions) - Seaborn')
plt.xlabel('Box Office Revenue (Millions)')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""### Observation

Which revenue range dominates?

### Business Decision

```text
Target profitable categories.
```
"""



"""---

## Chart 3

Genre Distribution
"""

plt.figure(figsize=(10, 6))
sns.countplot(x='Genre', data=df.dropna(subset=['Genre']), palette='viridis', order=df['Genre'].value_counts().index, hue='Genre', legend=False)
plt.title('Distribution of Movie Genres - Seaborn')
plt.xlabel('Genre')
plt.ylabel('Number of Movies')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""### Observation

Which genre appears most often?

### Business Decision

```text
Focus on audience preferences.
```

### Observation

Which genre appears most often?

### Business Decision

```text
Focus on audience preferences.
```
"""



"""---

## Chart 4

Rating vs Revenue
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(x='IMDB_Rating', y='Box_Office_Millions', data=df.dropna(subset=['IMDB_Rating', 'Box_Office_Millions']))
plt.title('IMDB Rating vs. Box Office Revenue (Millions) - Seaborn')
plt.xlabel('IMDB Rating')
plt.ylabel('Box Office Revenue (Millions)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""### Observation

Do higher-rated movies earn more revenue?

### Student Answer
"""

plt.figure(figsize=(8, 6))
sns.boxplot(y='Box_Office_Millions', data=df.dropna(subset=['Box_Office_Millions']))
plt.title('Box Office Revenue Distribution (Millions) - Seaborn')
plt.ylabel('Box Office Revenue (Millions)')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""Higher-rated movies (e.g., above 8.0) show a tendency towards higher box office revenue, with several top-grossing movies also having high IMDB ratings. However, there isn't a perfectly linear correlation, as some highly-rated movies have moderate revenue, and some moderately-rated movies still achieve high revenue."""



"""### Business Decision

```text
Invest in quality productions.
```

---

## Chart 5

Revenue Boxplot
"""



"""### Observation

Are there unusually high-grossing movies?

### Student Answer

The boxplot for Box Office Revenue reveals the spread of movie earnings. The central box represents the interquartile range (IQR), showing where the middle 50% of movies fall in terms of revenue. The line inside the box is the median revenue. The 'whiskers' extend to the most extreme data points within 1.5 times the IQR from the box. Any points beyond the whiskers are considered outliers, indicating movies with unusually high or low earnings compared to the rest of the dataset. This helps in quickly identifying potential blockbusters or underperforming films.
"""



"""### Business Decision

```text
Study blockbuster strategies.
```
"""



"""---

# FINAL MINI PROJECT

## Part 1

How many movies exist?
"""

print(len(df))

average_rating = df['IMDB_Rating'].mean()
print(f"Average Movie Rating: {average_rating:.2f}")

average_revenue = df['Box_Office_Millions'].mean()
print(f"Average Movie Revenue: ${average_revenue:.2f} million")

average_duration = df['Duration_Minutes'].mean()
print(f"Average Movie Duration: {average_duration:.2f} minutes")

highest_rated_movie_mini = df.loc[df['IMDB_Rating'].idxmax()]
display(highest_rated_movie_mini)

highest_revenue_movie_mini = df.loc[df['Box_Office_Millions'].idxmax()]
display(highest_revenue_movie_mini)

# The 'performance_category' function was already defined and the 'Performance_Category' column was already created earlier.
# Re-running the creation of the column here to align with the 'FINAL MINI PROJECT' structure.

df['Performance_Category'] = df['IMDB_Rating'].apply(performance_category)
display(df.head())

performance_counts_mini = df['Performance_Category'].value_counts()
print("Performance Category Counts:")
print(performance_counts_mini)

import matplotlib.pyplot as plt

# Chart 1: Distribution of IMDB Ratings
plt.figure(figsize=(10, 6))
plt.hist(df['IMDB_Rating'].dropna(), bins=10, edgecolor='black')
plt.title('Distribution of IMDB Ratings (Matplotlib)')
plt.xlabel('IMDB Rating')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

# Chart 2: Distribution of Box Office Revenue
plt.figure(figsize=(10, 6))
plt.hist(df['Box_Office_Millions'].dropna(), bins=10, edgecolor='black')
plt.title('Distribution of Box Office Revenue (Millions) (Matplotlib)')
plt.xlabel('Box Office Revenue (Millions)')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

# Chart 3: Distribution of Movie Durations
plt.figure(figsize=(10, 6))
plt.hist(df['Duration_Minutes'].dropna(), bins=10, edgecolor='black')
plt.title('Distribution of Movie Durations (Minutes) (Matplotlib)')
plt.xlabel('Duration (Minutes)')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""### Part 10

Create 3 Seaborn Charts.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Chart 1: Distribution of IMDB Ratings (Seaborn Histplot)
plt.figure(figsize=(10, 6))
sns.histplot(df['IMDB_Rating'].dropna(), bins=10, kde=True)
plt.title('Distribution of IMDB Ratings (Seaborn)')
plt.xlabel('IMDB Rating')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

# Chart 2: Distribution of Box Office Revenue (Seaborn Histplot)
plt.figure(figsize=(10, 6))
sns.histplot(df['Box_Office_Millions'].dropna(), bins=10, kde=True)
plt.title('Distribution of Box Office Revenue (Millions) (Seaborn)')
plt.xlabel('Box Office Revenue (Millions)')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

# Chart 3: Distribution of Movie Durations (Seaborn Histplot)
plt.figure(figsize=(10, 6))
sns.histplot(df['Duration_Minutes'].dropna(), bins=10, kde=True)
plt.title('Distribution of Movie Durations (Minutes) (Seaborn)')
plt.xlabel('Duration (Minutes)')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""---

## Part 2

Average Rating?
"""

average_rating = df['IMDB_Rating'].mean()
print(f"Average Movie Rating: {average_rating:.2f}")

"""---

## Part 3

Average Revenue?
"""

average_revenue = df['Box_Office_Millions'].mean()
print(f"Average Movie Revenue: ${average_revenue:.2f} million")

"""---

## Part 4

Average Duration?
"""

average_duration = df['Duration_Minutes'].mean()
print(f"Average Movie Duration: {average_duration:.2f} minutes")

"""---

## Part 5

Highest Rated Movie?
"""

highest_rated_movie_mini = df.loc[df['IMDB_Rating'].idxmax()]
display(highest_rated_movie_mini)

"""---

## Part 6

Highest Revenue Movie?
"""

highest_revenue_movie_mini = df.loc[df['Box_Office_Millions'].idxmax()]
display(highest_revenue_movie_mini)

"""---

## Part 7

Create Performance_Category Column.
"""

# The 'performance_category' function was already defined and the 'Performance_Category' column was already created earlier.
# Re-running the creation of the column here to align with the 'FINAL MINI PROJECT' structure.
df['Performance_Category'] = df['IMDB_Rating'].apply(performance_category)
display(df.head())

"""---

## Part 8

Count:

```text
Poor
Average
Excellent
```
"""

performance_counts_mini = df['Performance_Category'].value_counts()
print("Performance Category Counts:")
print(performance_counts_mini)

"""---

## Part 9

Create 3 Matplotlib Charts.
"""

import matplotlib.pyplot as plt

# Chart 1: Distribution of IMDB Ratings
plt.figure(figsize=(10, 6))
plt.hist(df['IMDB_Rating'].dropna(), bins=10, edgecolor='black')
plt.title('Distribution of IMDB Ratings (Matplotlib)')
plt.xlabel('IMDB Rating')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

# Chart 2: Distribution of Box Office Revenue
plt.figure(figsize=(10, 6))
plt.hist(df['Box_Office_Millions'].dropna(), bins=10, edgecolor='black')
plt.title('Distribution of Box Office Revenue (Millions) (Matplotlib)')
plt.xlabel('Box Office Revenue (Millions)')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

# Chart 3: Distribution of Movie Durations
plt.figure(figsize=(10, 6))
plt.hist(df['Duration_Minutes'].dropna(), bins=10, edgecolor='black')
plt.title('Distribution of Movie Durations (Minutes) (Matplotlib)')
plt.xlabel('Duration (Minutes)')
plt.ylabel('Number of Movies')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""---

## Part 10

Create 3 Seaborn Charts.

### Part 11

#### 5 Business Recommendations:

1.  **Address Data Quality Issues:** Prioritize cleaning the dataset by handling missing values, removing duplicate records, and correcting impossible negative values for duration, IMDB rating, and box office revenue. Accurate data is fundamental for reliable analysis and decision-making.
2.  **Invest in High-Quality Productions:** The analysis indicates a tendency for higher-rated movies to generate more revenue. Studios should focus on producing films with strong scripts, direction, and acting to achieve higher IMDB ratings, which could lead to better box office performance.
3.  **Strategic Genre Focus:** While Thriller and Drama genres appear frequently, 'Action' movies demonstrate strong revenue potential. Studios should continue to analyze genre popularity and profitability to strategically invest in genres that align with audience demand and revenue goals.
4.  **Optimize Movie Duration:** The distribution of movie durations shows a common range. Further analysis into optimal movie lengths for different genres could help in production planning to maximize audience engagement and box office returns.
5.  **Monitor Performance Categories:** Regularly track movie performance categories (Poor, Average, Excellent) to quickly identify underperforming films and genres. Implement post-release analysis for 'Poor' movies to understand reasons for low ratings and revenue, helping to refine future production strategies and avoid similar pitfalls.

### Part 11

#### 5 Business Recommendations:

1.  **Address Data Quality Issues:** Prioritize cleaning the dataset by handling missing values, removing duplicate records, and correcting impossible negative values for duration, IMDB rating, and box office revenue. Accurate data is fundamental for reliable analysis and decision-making.
2.  **Invest in High-Quality Productions:** The analysis indicates a tendency for higher-rated movies to generate more revenue. Studios should focus on producing films with strong scripts, direction, and acting to achieve higher IMDB ratings, which could lead to better box office performance.
3.  **Strategic Genre Focus:** While Thriller and Drama genres appear frequently, 'Action' movies demonstrate strong revenue potential. Studios should continue to analyze genre popularity and profitability to strategically invest in genres that align with audience demand and revenue goals.
4.  **Optimize Movie Duration:** The distribution of movie durations shows a common range. Further analysis into optimal movie lengths for different genres could help in production planning to maximize audience engagement and box office returns.
5.  **Monitor Performance Categories:** Regularly track movie performance categories (Poor, Average, Excellent) to quickly identify underperforming films and genres. Implement post-release analysis for 'Poor' movies to understand reasons for low ratings and revenue, helping to refine future production strategies and avoid similar pitfalls.

---

## Part 11

Write 5 Business Recommendations.

Example:

```text
Most movies are rated between 6 and 8.

Studios should analyze excellent movies for best practices.

High-rated movies tend to generate higher revenue.

Action movies generate strong box-office results.

Marketing budgets should focus on top-performing genres.
```
"""

print("### 5 Business Recommendations:\n")
print("1. Address Data Quality Issues: Prioritize cleaning the dataset by handling missing values, removing duplicate records, and correcting impossible negative values for duration, IMDB rating, and box office revenue. Accurate data is fundamental for reliable analysis and decision-making.\n")
print("2. Invest in High-Quality Productions: The analysis indicates a tendency for higher-rated movies to generate more revenue. Studios should focus on producing films with strong scripts, direction, and acting to achieve higher IMDB ratings, which could lead to better box office performance.\n")
print("3. Strategic Genre Focus: While Thriller and Drama genres appear frequently, 'Action' movies demonstrate strong revenue potential. Studios should continue to analyze genre popularity and profitability to strategically invest in genres that align with audience demand and revenue goals.\n")
print("4. Optimize Movie Duration: The distribution of movie durations shows a common range. Further analysis into optimal movie lengths for different genres could help in production planning to maximize audience engagement and box office returns.\n")
print("5. Monitor Performance Categories: Regularly track movie performance categories (Poor, Average, Excellent) to quickly identify underperforming films and genres. Implement post-release analysis for 'Poor' movies to understand reasons for low ratings and revenue, helping to refine future production strategies and avoid similar pitfalls.")
